### ISSUE TITLE
返回页面回到顶部了

### ISSUE THREAD

**Issue by atjiu** [wuyanwen/dianpinPlus#1]
问题描述可见 ：https://cnodejs.org/topic/59a424cdbc6d95370812890b

目测是react-router(v4) 的坑，我是通过换成了react-router(v2) 外加上react-router-scroll解决的

大大如果在react-router(v4) 下也解决了，麻烦at我一下，谢谢了

**Comment by wuyanwen** [comment]
#### 原理确实是你说的这样
> 可以在List页面加载完数据后就保存它的state到redux/localStorage里，从Detail返回到List页面的时候直接取就可以了，另外回到之前滚动的位置也可以在跳转前存一下滚动的位置scrollTop，从Detail返回的时候，可以设置一下
#### 目前react-router(v4)查看源码，本身确实没有你说的这个功能的，就像按需加载组件，react-router(v4)本身也没有实现，需要借助第三方的bundle-loader，在没找到第三方的情况下，只有按照你上面的想法实现了。

**Comment by atjiu** [comment]
那你这项目要修复这个问题吗？

**Comment by wuyanwen** [comment]
想修复这问题，需要写个第三方插件，目前时间紧，暂时不优化你说的这个功能点。之后时间充裕了，会写个独立的组件，你可以先star这个项目，后期会写个类似于vue中的[vuet](https://github.com/medatc/vuet)，就是专门解决你这问题的vue组件，只不过咱们是要写成react的。
