### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by ZHENGGEGE** [wuyanwen/dianpinPlus#4]
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/suzheng/.babelrc" at 0, attempted to resolve relative to "/Users/suzheng"

你好，刚刚开始学react，安装项目指示操作为什么会报这个错，从新卸载  npm install 也不行

**Comment by wuyanwen** [comment]
可能你网络问题,这个错误提示就是说明你缺少包呢,`npm install transform-runtime --save-dev`
